version: "3"

services:
  api:
    build:
      context: .
      dockerfile: .docker/elixir/Dockerfile
    container_name: elixir_api
    ports:
      - 4000:4000
    volumes:
      - ./src:/app
    depends_on:
      - db
    networks:
      - api_web

  db:
    image: postgres:12-alpine
    container_name: elixir_db
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: elixr
    ports:
      - 5432:5432
    volumes:
      - .docker/db:/var/lib/mysql
    networks:
      - api_web

networks: 
  api_web: